set_property MARK_DEBUG false [get_nets {instr_addr[1]}]
set_property MARK_DEBUG false [get_nets {instr_addr[8]}]
set_property MARK_DEBUG false [get_nets {instr_addr[16]}]
set_property MARK_DEBUG false [get_nets {instr_addr[22]}]
set_property MARK_DEBUG false [get_nets {instr_addr[23]}]
set_property MARK_DEBUG false [get_nets {instr_addr[29]}]
set_property MARK_DEBUG false [get_nets {instr_addr[7]}]
set_property MARK_DEBUG false [get_nets {instr_addr[3]}]
set_property MARK_DEBUG false [get_nets {instr_addr[6]}]
set_property MARK_DEBUG false [get_nets {instr_addr[9]}]
set_property MARK_DEBUG false [get_nets {instr_addr[14]}]
set_property MARK_DEBUG false [get_nets {instr_addr[17]}]
set_property MARK_DEBUG false [get_nets {instr_addr[18]}]
set_property MARK_DEBUG false [get_nets {instr_addr[24]}]
set_property MARK_DEBUG false [get_nets {instr_addr[28]}]
set_property MARK_DEBUG false [get_nets {instr_addr[4]}]
set_property MARK_DEBUG false [get_nets {instr_addr[0]}]
set_property MARK_DEBUG false [get_nets {instr_addr[2]}]
set_property MARK_DEBUG false [get_nets {instr_addr[10]}]
set_property MARK_DEBUG false [get_nets {instr_addr[11]}]
set_property MARK_DEBUG false [get_nets {instr_addr[12]}]
set_property MARK_DEBUG false [get_nets {instr_addr[20]}]
set_property MARK_DEBUG false [get_nets {instr_addr[26]}]
set_property MARK_DEBUG false [get_nets {instr_addr[31]}]
set_property MARK_DEBUG false [get_nets {instr_addr[5]}]
set_property MARK_DEBUG false [get_nets {instr_addr[13]}]
set_property MARK_DEBUG false [get_nets {instr_addr[15]}]
set_property MARK_DEBUG false [get_nets {instr_addr[19]}]
set_property MARK_DEBUG false [get_nets {instr_addr[21]}]
set_property MARK_DEBUG false [get_nets {instr_addr[25]}]
set_property MARK_DEBUG false [get_nets {instr_addr[27]}]
set_property MARK_DEBUG false [get_nets {instr_addr[30]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[2]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[8]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[14]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[17]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[21]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[25]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[27]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[5]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[3]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[4]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[6]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[13]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[18]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[24]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[26]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[31]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[28]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[29]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[7]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[9]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[10]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[15]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[20]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[23]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[30]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[0]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[1]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[11]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[12]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[16]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[19]}]
set_property MARK_DEBUG false [get_nets {instr_rdata[22]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {bus/data_addr_i[2]} {bus/data_addr_i[3]} {bus/data_addr_i[4]} {bus/data_addr_i[5]} {bus/data_addr_i[6]} {bus/data_addr_i[7]} {bus/data_addr_i[8]} {bus/data_addr_i[9]} {bus/data_addr_i[10]} {bus/data_addr_i[11]} {bus/data_addr_i[12]} {bus/data_addr_i[13]} {bus/data_addr_i[14]} {bus/data_addr_i[15]} {bus/data_addr_i[16]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {bus/instr_addr[2]} {bus/instr_addr[3]} {bus/instr_addr[4]} {bus/instr_addr[5]} {bus/instr_addr[6]} {bus/instr_addr[7]} {bus/instr_addr[8]} {bus/instr_addr[9]} {bus/instr_addr[10]} {bus/instr_addr[11]} {bus/instr_addr[12]} {bus/instr_addr[13]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {bus/instr_rdata[0]} {bus/instr_rdata[1]} {bus/instr_rdata[2]} {bus/instr_rdata[3]} {bus/instr_rdata[4]} {bus/instr_rdata[5]} {bus/instr_rdata[6]} {bus/instr_rdata[7]} {bus/instr_rdata[8]} {bus/instr_rdata[9]} {bus/instr_rdata[10]} {bus/instr_rdata[11]} {bus/instr_rdata[12]} {bus/instr_rdata[13]} {bus/instr_rdata[14]} {bus/instr_rdata[15]} {bus/instr_rdata[16]} {bus/instr_rdata[17]} {bus/instr_rdata[18]} {bus/instr_rdata[19]} {bus/instr_rdata[20]} {bus/instr_rdata[21]} {bus/instr_rdata[22]} {bus/instr_rdata[23]} {bus/instr_rdata[24]} {bus/instr_rdata[25]} {bus/instr_rdata[26]} {bus/instr_rdata[27]} {bus/instr_rdata[28]} {bus/instr_rdata[29]} {bus/instr_rdata[30]} {bus/instr_rdata[31]}]]
connect_debug_port u_ila_1/probe2 [get_nets [list bus/rx]]
connect_debug_port u_ila_1/probe3 [get_nets [list bus/tx]]








create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list cv32e40p_top/core_i/sleep_unit_i/core_clock_gate_i/clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {bus/wea[0]} {bus/wea[1]} {bus/wea[2]} {bus/wea[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 11 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {data_addr[2]} {data_addr[3]} {data_addr[4]} {data_addr[5]} {data_addr[6]} {data_addr[7]} {data_addr[8]} {data_addr[9]} {data_addr[10]} {data_addr[11]} {data_addr[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {data_wdata[0]} {data_wdata[1]} {data_wdata[2]} {data_wdata[3]} {data_wdata[4]} {data_wdata[5]} {data_wdata[6]} {data_wdata[7]} {data_wdata[8]} {data_wdata[9]} {data_wdata[10]} {data_wdata[11]} {data_wdata[12]} {data_wdata[13]} {data_wdata[14]} {data_wdata[15]} {data_wdata[16]} {data_wdata[17]} {data_wdata[18]} {data_wdata[19]} {data_wdata[20]} {data_wdata[21]} {data_wdata[22]} {data_wdata[23]} {data_wdata[24]} {data_wdata[25]} {data_wdata[26]} {data_wdata[27]} {data_wdata[28]} {data_wdata[29]} {data_wdata[30]} {data_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {irq[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {data_rdata[0]} {data_rdata[1]} {data_rdata[2]} {data_rdata[3]} {data_rdata[4]} {data_rdata[5]} {data_rdata[6]} {data_rdata[7]} {data_rdata[8]} {data_rdata[9]} {data_rdata[10]} {data_rdata[11]} {data_rdata[12]} {data_rdata[13]} {data_rdata[14]} {data_rdata[15]} {data_rdata[16]} {data_rdata[17]} {data_rdata[18]} {data_rdata[19]} {data_rdata[20]} {data_rdata[21]} {data_rdata[22]} {data_rdata[23]} {data_rdata[24]} {data_rdata[25]} {data_rdata[26]} {data_rdata[27]} {data_rdata[28]} {data_rdata[29]} {data_rdata[30]} {data_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 11 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {instr_addr[2]} {instr_addr[3]} {instr_addr[4]} {instr_addr[5]} {instr_addr[6]} {instr_addr[7]} {instr_addr[8]} {instr_addr[9]} {instr_addr[10]} {instr_addr[11]} {instr_addr[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {bus/UART/uart_core/rx_state[0]} {bus/UART/uart_core/rx_state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list bus/data_mem_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list bus/gpio_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list bus/timer_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk]
